# C:\Users\hecto\Documents\Prg_locales\I_R_G\.streamlit\secrets.toml

[postgres]
host = "aws-1-sa-east-1.pooler.supabase.com"
port = 6543
dbname = "postgres"
# FORMATO: usuario.ID_DEL_PROYECTO
user = "postgres.extrlcvcgypwazxipvqm"
password = "IJoFJbT8Qj0Q0w5m"